[tool.pylint.'MESSAGES CONTROL']

disable = [
	"too-many-arguments",
	"too-many-locals",
    "logging-fstring-interpolation",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "unspecified-encoding",
]
