name: Python Linting and Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run mypy
      run: pipenv run mypy .

    - name: Run pylint
      run: pipenv run pylint **/*.py

    - name: Run black
      run: pipenv run black --check .

    - name: Run isort
      run: pipenv run isort --check-only .

